### ISSUE TITLE
Suggestion: Improve documentation for MaterialPropertyDebugMenu features

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#1]
Material Prefs Sampleに関して、
Materialの変数名(_Color, _SmoothnessTextureChannel等)を手動でcomponentに登録する必要がないですが、実際にコードを使ってみないとそれが分からないです。 
readmeやMaterialPropertyDebugMenu.csのコメントに自動的にPrefsGUIはmaterialの変数名を取得してくれることを書けばPrefsGUIの使い方がより分かりやすくなります。

![prefsgui material variables](https://user-images.githubusercontent.com/6245912/27680063-93cd7ebc-5cf5-11e7-885f-14cf9db61389.JPG)

**Comment by fuqunaga** [comment]
readmeの文章とgifでわかるんじゃないかな？
