### ISSUE TITLE
GUIUtil classes are not inside a namespace

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#11]
This could create conflicts.
Please move them to a new namespace or move them to the PrefsSync namepsace.

**Comment by fuqunaga** [comment]
i will consider after #7

**Comment by Innovative-Ideas** [comment]
When you included GUIUtil classes inside your SyncUtil repository, you put them in a separate name space (presumably to avoid a conflict with PrefsGUI)
https://github.com/fuqunaga/SyncUtil/blob/master/Assets/Packages/SyncUtil/Scripts/GUIUtil/GUIUtil.cs

I believe it's a good coding standard to always put your classes in a namespace to avoid potential conflicts.
So I hope you'll reconsider this feedback sooner.

**Comment by fuqunaga** [comment]
yes, I know.
So I am looking forward to seeing unity packet manager.
I'd like to think of the namespace name that is good since I grasp the mechanism.

if you hurry up,  you can fork this repository and make it as you like.

**Comment by fuqunaga** [comment]
GUIUtil is now [RapidGUI](https://github.com/fuqunaga/RapidGUI) as another package.
