### ISSUE TITLE
PrefsGUISync's NetworkServer.SpawnObjects() seems redundant

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#12]
Unityは自動的にNetworkServer.SpawnObjects()を読んでいますので、
わざと、PrefsGUISync.OnServerStart()はSpawnObjectsを呼ばなくてもいいでしょう。

![networkserver spawn objects](https://user-images.githubusercontent.com/6245912/36595060-1ca38aa6-18e4-11e8-9c3f-16bb4bbc6373.JPG)

**Comment by fuqunaga** [comment]
PrefsGUISync は[PrefsGUISyncUNET](https://github.com/fuqunaga/PrefsGUISyncUNET)に分離しました。
