### ISSUE TITLE
Prefabごとに、違うMaterialの変数の価が設定出来るサンプルを作れば便利そうです。

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#2]
Prefabごとに、違うMaterial変数の価が設定出来るメニューのサンプルがあればいいなと思っています。

例えば、
三つの敵のprefabが有って、
全部の敵を同じMaterialとShaderでレンダリングしていますが、
敵の種類(prefab)によっては違う変数の価を設定したいです。

**Comment by Innovative-Ideas** [comment]
一つの解決方法は、
敵の種類ごとに、違うmaterialを作って、
各materialの名前を別々にして、
各materialに同じシェーダーを付ける
ことだと思い付きました。

**Comment by fuqunaga** [comment]
僕も別々のmaterialにするべきだと思います
