### ISSUE TITLE
Suggestion: 設定ファイルのsave/loadパスに関して、streaming asserts + customパスを対応すれば良い

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#3]
設定ファイルをgitにコミットしたいですので、git repository内のstreaming assetsのカスタムパスでファイルをsave/loadが出来ればいいなぁと思っています。

**Comment by Innovative-Ideas** [comment]
一応、私のforkでこれを対応しました。

**Comment by fuqunaga** [comment]
- streaming assets 以下とは別のパスのバリエーションは必要ないのか。Documents下や任意のフォルダなど
- パスを覚えておくのはどこか？sceneやprefabファイル？起動毎にユーザーが指定？
- パスをどのタイミングで指定するか
　Loadするまえに指定したいが、static constructorでLoadするのは気に入っているのでこれより先の処理を保証できるか

あたりが気になるところです。
いまのところ１アプリケーション１KVSのPlayerPrefsの設計を模してますが、
そもそもその辺から考えどころな気もします。

**Comment by Innovative-Ideas** [comment]
> streaming assets 以下とは別のパスのバリエーションは必要ないのか。

答え：For streaming assets, different exhibits may use different settings.  In order to save those settings files in git, separate paths are used. 

> Documents下や任意のフォルダなど

答え：PrefsGUI alsways used the same file name to save its settings.  For Documents or other locations outside of streaming assets, sub folders are also necessary.  Consider developing two different applications that both usePrefsGUI.  Without a sub folder, Each one will read the same settings file.  This is undesirable.  

> パスを覚えておくのはどこか？sceneやprefabファイル？起動毎にユーザーが指定？

答え：今まではSceneの中にあるgameobjectのcomponentにsubfolderのパスを登録しています。アプリをビルドすればsubfolderのパスは固定になります。

> パスをどのタイミングで指定するか
> 　Loadするまえに指定したいが、static constructorでLoadするのは気に入っているのでこれより先の処理を保証できるか

答え：上記の答えと同じprefabはAwake()にPrefsGUIにsubfolderのパスを設定してから、もう一回ファイルをロードしています。
https://github.com/Innovative-Ideas/PrefsGUI/blob/master/Assets/Packages/PrefsGUIMenuSystem/Scripts/PrefsGUISettings.cs

**Comment by fuqunaga** [comment]
> For streaming assets, different exhibits may use different settings. In order to save those settings files in git, separate paths are used.

gitなどに保存するなら、ScriptableObjectやsceneファイル、prefabや独自のファイルに保存するのがよいと思います。
PrefsGUIはPlayerPrefsの挙動にのっとり、同アプリ別ファイルはサポートせず、その分シンプルにしたいです。


> PrefsGUI alsways used the same file name to save its settings. For Documents or other locations outside of streaming assets, sub folders are also necessary. Consider developing two different applications that both usePrefsGUI. Without a sub folder, Each one will read the same settings file. This is undesirable.

PrefsGUIは同じファイル名で保存しますが、アプリケーションごとに保存するパスが違います。
https://docs.unity3d.com/ja/current/ScriptReference/Application-persistentDataPath.html


> 上記の答えと同じprefabはAwake()にPrefsGUIにsubfolderのパスを設定してから、もう一回ファイルをロードしています。

これはよくない方法です。
なぜstatic constructorでLoad()しているか考えてみましたか？

アプリケーション側で設定しない限りAwake()の呼び出し順は未定義だったと思います。
PrefsGUIのLoadされた値を使いたい処理（たとえばほかのGameObjectのAwake()）より先に、パスを設定するAwake()が呼ばれるようにアプリケーション側が気をつけて設定しなくてはいけません。
このデメリットより、PrefsGUIのパスは決まっているが通常の処理ではかならず正しいファイルがLoad()済みであることが保証されているメリットのほうが良いと考えます。
