### ISSUE TITLE
Suggestion: "ReadOnly" mode for PrefsGUI type variables

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#5]
Add an extra boolean to all the type variables called readOnly.
When false, PrefsGUI's GUI is displayed as normal.
When true, PrefsGUI's GUI is displayed using labels so the contents cannot be changed.

Use Case 1: Some variables are only editable by the server, but I want to display them on the client in read only format.
Use Case 2: Same as Use Case 1 except, additionally, i want to allow a client computer to edit just the variables associated with it. So on the server and 1 client, the PrefsGUI is editable.  On all other clients the PrefsGUI is read only.

**Comment by fuqunaga** [comment]
Use Case 1、２どちらもPrefsGUISyncで目的を果たせてそうな気がしますがどうでしょう？

**Comment by Innovative-Ideas** [comment]
PrefsGUISyncで同期してないパラメーターやデータです。例えば、treeの構造体です。
ですが、GUIをdrawする時にPrefsGUI内のvector4クラスを利用しています。VectorのデータをGUIにdrawする時にそのクラスは便利です。

**Comment by fuqunaga** [comment]
もしデータの保存ではなくGUIだけが必要であれば、PrefsGUIに含まれるGUIUtilが使えるかもしれません。
また、ReadOnlyにする方法としてUnity標準のGUI.enableもヒントになるかもしれません。

PrefsGUIをただのGUI drawするためだけに使っており、
そのためにReadOnlyの機能を入れるのはこのライブラリの目的からはずれていると思います。
＊もちろんそのように使ってもown riskである分には問題ありません

**Comment by Innovative-Ideas** [comment]
PrefsGUIの代わりにGUIUtilで進んだたら良いです。それを使うようにしました。
GUI.enableのヒントも役に立ちました。それで大体想像した機能が出来ました。
一つだけの残念のはGUIUtil.Fieldのラベルのテキストも半透明になってしまいます。

PrefsGUIのglobal設定にsolidLabelWhenDisabledを追加して、
Fieldの中に以下のようにそれは解決出来るかもしれません。
ラベルをdrawする時に
var backup = GUI.enabled;
if(GUI.enabled == false && solidLabelWhenDisabled)
     GUI.enabled = true;

// draw label
...

GUI.enabled = backup

**Comment by fuqunaga** [comment]
ラベルも半透明になるのはUnityEditorの挙動と一致してるので個人的には問題ないと思います。

もし、globalで設定できるようにすると今度は「インスタンスごとに設定したい」とった要望も出て来るかもしれないので、なにかやるなら要望をためて需要のバランスを把握してからにしたいと思います
