### ISSUE TITLE
Suggestion:GUI Utilを複数ファイルに分割すれば良い

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#6]
There's a lot of useful classes in GUIUtil.cs.
1. The classes deserve to be highlighted more so it is more apparent to people what features / functions are in your library.  Putting them in seperate files will accomplish this.
2. There is a lot of code in GUIUtil.cs so I see you make excessive use of #region.  Separating the code into multiple files will mean you can use #region less and still maintain readability.

**Comment by fuqunaga** [comment]
OK. Please send me a pull request.
