### ISSUE TITLE
Suggestion: GUIUtilを別の単位リポジトリに独立すればどう思っていますか。

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#7]
GUIUtilはPrefsGUIに依存してないし、そのコードだけは役に立ちますから、独立することはありかもしれません。参考まで、提案しました。

**Comment by fuqunaga** [comment]
ちょっと考えてます。
とりあえずUnityオフィシャルのPackageManagerが出るまでは様子見のつもりです。
