### ISSUE TITLE
GUIUtilのUnparsedStringは何ですか。

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/PrefsGUI#8]
以下のことを書いた方が良さそうです。

- ParseString対Unparsed Stringの説明
- Unparsed Stringを利用するメリットとか、use case
- など

**Comment by fuqunaga** [comment]
主にfloatを入力する途中で、"0."など「floatにparseできないけどGUIとして入力を継続できるようにする」ために使用しています
